name: server_app
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Matt Eiben <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  analysis_server_lib: ^0.1.4+2
  archive: ^2.0.5
  args: ^1.4.2
  discoveryapis_generator: ^0.9.10
  logging: '>=0.9.0 <0.12.0'
  path: ^1.3.0
  rpc: '^0.6.0'
  shelf: ^0.7.2

#dev_dependencies:
#  test: ^1.0.0
